version: '3'

services:

  auth-service:
    image: mihago/authentication-service:latest
    container_name: auth_service
    restart: unless-stopped
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-service.rule=Host(`auth.omgapp.pp.ua`)"
      - "traefik.http.routers.auth-service.entrypoints=websecure"
      - "traefik.http.routers.auth-service.tls=true"
      - "traefik.http.routers.auth-service.tls.certresolver=letsEncrypt"
    volumes:
      - "./config/production.json:/home/node/app/config/production.json:ro"
    
  reverse-proxy:
    image: traefik:v2.9
    container_name: traefik
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.dashboard.rule=Host(`auth.omgapp.pp.ua`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$7.JJ7f/D$$73liZlkkwPPJsIcTc6elb."
      - "traefik.http.routers.dashboard.middlewares=auth"

    
    ports:
      - "443:443"
      - "80:80"

    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/traefik.yml:ro"